server:
  port: 8080

spring:
  application:
    name: @artifactId@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://soul-mysql:3306/soulTable?useUnicode=true&characterEncoding=utf8
    username: root
    password: Soul-table-123
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化连接数大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 验证数据库连接的有效性
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,slf4j


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

logging:
  config: classpath:log4j2-spring.xml
  level:
    com.alibaba.nacos.client.naming: error
